import { useRef } from "react";
import { drawImage } from './imageEditorDrawing';

export function useImageEditorDraw(
  canvasRef: React.MutableRefObject<HTMLCanvasElement | null>,
  imgRef: React.MutableRefObject<HTMLImageElement | null>,
  originalImgRef: React.MutableRefObject<HTMLImageElement | null>,
  previewOriginalRef: React.MutableRefObject<boolean>,
  offset: { x: number; y: number },
  sel: any,
  exposureRef: React.MutableRefObject<number>,
  contrastRef: React.MutableRefObject<number>,
  saturationRef: React.MutableRefObject<number>,
  temperatureRef: React.MutableRefObject<number>,
  vignetteRef: React.MutableRefObject<number>,
  frameColorRef: React.MutableRefObject<'white' | 'black'>,
  frameThicknessRef: React.MutableRefObject<number>,
  selectedFilterRef: React.MutableRefObject<string>,
  filterStrengthRef: React.MutableRefObject<number>,
  grainRef: React.MutableRefObject<number>,
  softFocusRef: React.MutableRefObject<number>,
  fadeRef: React.MutableRefObject<number>,
  overlayRef: React.MutableRefObject<any>,
  rotationRef: React.MutableRefObject<number>,
  dashOffsetRef: React.MutableRefObject<number>,
  computeImageLayout: () => any,
  // special effects refs
  ditherMethodRef?: React.MutableRefObject<'none' | 'floyd-steinberg' | 'ordered' | 'bayer8' | 'atkinson' | 'burkes' | 'stucki' | 'sierra' | 'jjn'>,
  ditherLevelsRef?: React.MutableRefObject<number>,
  ditherColorModeRef?: React.MutableRefObject<'bw' | 'color'>,
  ditherPaletteRef?: React.MutableRefObject<'auto' | 'websafe' | 'cga16' | 'ega64' | 'mac16' | 'win16'>,
  ditherCustomPaletteRef?: React.MutableRefObject<string>,
  pixelSizeRef?: React.MutableRefObject<number>,
  pixelShapeRef?: React.MutableRefObject<'square' | 'circle'>,
  pixelSampleRef?: React.MutableRefObject<'average' | 'nearest'>,
  asciiEnabledRef?: React.MutableRefObject<boolean>,
  asciiCellSizeRef?: React.MutableRefObject<number>,
  asciiCharsetRef?: React.MutableRefObject<string>,
  asciiInvertRef?: React.MutableRefObject<boolean>,
  asciiColorRef?: React.MutableRefObject<boolean>,
  asciiOpacityRef?: React.MutableRefObject<number>,
  asciiBackgroundRef?: React.MutableRefObject<string>,
  asciiFontRef?: React.MutableRefObject<string>,
  asciiGammaRef?: React.MutableRefObject<number>,
  asciiBoldRef?: React.MutableRefObject<boolean>,
  asciiEdgeRef?: React.MutableRefObject<'none' | 'stroke'>,
  frameOverlayRef?: React.MutableRefObject<any>
) {
  const drawPendingRef = useRef(false);

  function draw(info?: any, overrides?: any, targetCanvas?: HTMLCanvasElement) {
    if (targetCanvas) {
      // synchronous for export
      return drawImage(
        canvasRef,
        imgRef,
        originalImgRef,
        previewOriginalRef,
        offset,
        sel,
        exposureRef,
        contrastRef,
        saturationRef,
        temperatureRef,
        vignetteRef,
        frameColorRef,
        frameThicknessRef,
        selectedFilterRef,
        filterStrengthRef,
        grainRef,
        softFocusRef,
        fadeRef,
        overlayRef,
        rotationRef,
        dashOffsetRef,
        computeImageLayout,
        ditherMethodRef,
        ditherLevelsRef,
        ditherColorModeRef,
        ditherPaletteRef,
        ditherCustomPaletteRef,
        pixelSizeRef,
        pixelShapeRef,
        pixelSampleRef,
        asciiEnabledRef,
        asciiCellSizeRef,
        asciiCharsetRef,
        asciiInvertRef,
        asciiColorRef,
        asciiOpacityRef,
        asciiBackgroundRef,
        asciiFontRef,
        asciiGammaRef,
        asciiBoldRef,
        asciiEdgeRef,
        info,
        overrides,
        targetCanvas,
        frameOverlayRef
      );
    }
    if (drawPendingRef.current) return; // skip if already pending
    drawPendingRef.current = true;
    requestAnimationFrame(() => {
      drawPendingRef.current = false;
      return drawImage(
        canvasRef,
        imgRef,
        originalImgRef,
        previewOriginalRef,
        offset,
        sel,
        exposureRef,
        contrastRef,
        saturationRef,
        temperatureRef,
        vignetteRef,
        frameColorRef,
        frameThicknessRef,
        selectedFilterRef,
        filterStrengthRef,
        grainRef,
        softFocusRef,
        fadeRef,
        overlayRef,
        rotationRef,
        dashOffsetRef,
        computeImageLayout,
        ditherMethodRef,
        ditherLevelsRef,
        ditherColorModeRef,
        ditherPaletteRef,
        ditherCustomPaletteRef,
        pixelSizeRef,
        pixelShapeRef,
        pixelSampleRef,
        asciiEnabledRef,
        asciiCellSizeRef,
        asciiCharsetRef,
        asciiInvertRef,
        asciiColorRef,
        asciiOpacityRef,
        asciiBackgroundRef,
        asciiFontRef,
        asciiGammaRef,
        asciiBoldRef,
        asciiEdgeRef,
        info,
        overrides,
        targetCanvas,
        frameOverlayRef
      );
    });
  }

  return { draw };
}