import { useMemo } from 'react';
import { applyEdit as applyEditAction, resetAdjustments as resetAdjustmentsAction, resetControlToDefault as resetControlToDefaultAction, bakeRotate90 as bakeRotate90Action, bakeRotateMinus90 as bakeRotateMinus90Action, applyCropOnly as applyCropOnlyAction, resetCrop as resetCropAction } from './imageEditor/imageEditorActions';

export function useImageEditorActions(
  setIsProcessing: (value: boolean) => void,
  imgRef: React.RefObject<HTMLImageElement | null>,
  canvasRef: React.RefObject<HTMLCanvasElement | null>,
  offset: { x: number; y: number },
  sel: { x: number; y: number; w: number; h: number } | null,
  exposure: number,
  contrast: number,
  saturation: number,
  temperature: number,
  vignette: number,
  frameColor: 'white' | 'black',
  frameThickness: number,
  selectedFilter: string,
  filterStrength: number,
  grain: number,
  softFocus: number,
  fade: number,
  // special effects state
  ditherMethod: 'none' | 'floyd-steinberg' | 'ordered' | 'bayer8' | 'atkinson' | 'burkes' | 'stucki' | 'sierra' | 'jjn',
  ditherLevels: number,
  ditherColorMode: 'bw' | 'color',
  ditherPalette: 'auto' | 'websafe' | 'cga16' | 'ega64' | 'mac16' | 'win16',
  ditherCustomPalette: string | undefined,
  pixelSize: number,
  pixelShape: 'square' | 'circle',
  pixelSample: 'average' | 'nearest',
  asciiEnabled: boolean,
  asciiCellSize: number,
  asciiCharset: string,
  asciiInvert: boolean,
  asciiColor: boolean,
  asciiOpacity: number | undefined,
  asciiBackground: string | undefined,
  asciiFont: string | undefined,
  asciiGamma: number | undefined,
  asciiBold: boolean | undefined,
  asciiEdge: 'none' | 'stroke' | undefined,
  asciiCharsetPreset: 'custom' | 'dense' | 'medium' | 'sparse' | 'blocks' | 'dots' | undefined,
  rotation: number,
  rotationRef: React.MutableRefObject<number>,
  onApply: (dataUrl: string, settings: any) => Promise<void>,
  setExposure: (value: number) => void,
  exposureRef: React.MutableRefObject<number>,
  setContrast: (value: number) => void,
  contrastRef: React.MutableRefObject<number>,
  setSaturation: (value: number) => void,
  saturationRef: React.MutableRefObject<number>,
  setTemperature: (value: number) => void,
  temperatureRef: React.MutableRefObject<number>,
  setVignette: (value: number) => void,
  vignetteRef: React.MutableRefObject<number>,
  setFrameColor: (value: 'white' | 'black') => void,
  frameColorRef: React.MutableRefObject<'white' | 'black'>,
  setFrameThickness: (value: number) => void,
  frameThicknessRef: React.MutableRefObject<number>,
  setSelectedFilter: (value: string) => void,
  selectedFilterRef: React.MutableRefObject<string>,
  setFilterStrength: (value: number) => void,
  filterStrengthRef: React.MutableRefObject<number>,
  setGrain: (value: number) => void,
  grainRef: React.MutableRefObject<number>,
  setSoftFocus: (value: number) => void,
  softFocusRef: React.MutableRefObject<number>,
  setFade: (value: number) => void,
  fadeRef: React.MutableRefObject<number>,
  // special refs + setters
  setDitherMethod: (v: 'none' | 'floyd-steinberg' | 'ordered' | 'bayer8' | 'atkinson' | 'burkes' | 'stucki' | 'sierra' | 'jjn') => void,
  ditherMethodRef: React.MutableRefObject<'none' | 'floyd-steinberg' | 'ordered' | 'bayer8' | 'atkinson' | 'burkes' | 'stucki' | 'sierra' | 'jjn'>,
  setDitherLevels: (v: number) => void,
  ditherLevelsRef: React.MutableRefObject<number>,
  setDitherColorMode: (v: 'bw' | 'color') => void,
  ditherColorModeRef: React.MutableRefObject<'bw' | 'color'>,
  setDitherPalette: (v: 'auto' | 'websafe' | 'cga16' | 'ega64' | 'mac16' | 'win16') => void,
  ditherPaletteRef: React.MutableRefObject<'auto' | 'websafe' | 'cga16' | 'ega64' | 'mac16' | 'win16'>,
  setDitherCustomPalette: (v: string) => void,
  ditherCustomPaletteRef: React.MutableRefObject<string>,
  setPixelSize: (v: number) => void,
  pixelSizeRef: React.MutableRefObject<number>,
  setPixelShape: (v: 'square' | 'circle') => void,
  pixelShapeRef: React.MutableRefObject<'square' | 'circle'>,
  setPixelSample: (v: 'average' | 'nearest') => void,
  pixelSampleRef: React.MutableRefObject<'average' | 'nearest'>,
  setAsciiEnabled: (v: boolean) => void,
  asciiEnabledRef: React.MutableRefObject<boolean>,
  setAsciiCellSize: (v: number) => void,
  asciiCellSizeRef: React.MutableRefObject<number>,
  setAsciiCharset: (v: string) => void,
  asciiCharsetRef: React.MutableRefObject<string>,
  setAsciiInvert: (v: boolean) => void,
  asciiInvertRef: React.MutableRefObject<boolean>,
  setAsciiColor: (v: boolean) => void,
  asciiColorRef: React.MutableRefObject<boolean>,
  setAsciiOpacity: (v: number) => void,
  asciiOpacityRef: React.MutableRefObject<number>,
  setAsciiBackground: (v: string) => void,
  asciiBackgroundRef: React.MutableRefObject<string>,
  setAsciiFont: (v: string) => void,
  asciiFontRef: React.MutableRefObject<string>,
  setAsciiGamma: (v: number) => void,
  asciiGammaRef: React.MutableRefObject<number>,
  setAsciiBold: (v: boolean) => void,
  asciiBoldRef: React.MutableRefObject<boolean>,
  setAsciiEdge: (v: 'none' | 'stroke') => void,
  asciiEdgeRef: React.MutableRefObject<'none' | 'stroke'>,
  setAsciiCharsetPreset: (v: 'custom' | 'dense' | 'medium' | 'sparse' | 'blocks' | 'dots') => void,
  overlay: { img: HTMLImageElement; blendMode: string; opacity: number } | null,
  setOverlay: (v: { img: HTMLImageElement; blendMode: string; opacity: number } | null) => void,
  overlayRef: React.MutableRefObject<{ img: HTMLImageElement; blendMode: string; opacity: number } | null>,
  frameOverlay: { img: HTMLImageElement; opacity: number } | null,
  setFrameOverlay: (v: { img: HTMLImageElement; opacity: number } | null) => void,
  frameOverlayRef: React.MutableRefObject<{ img: HTMLImageElement; opacity: number } | null>,
  setRotation: (value: number) => void,
  setSel: (value: { x: number; y: number; w: number; h: number } | null) => void,
  cropRatio: React.MutableRefObject<number | null>,
  setPresetIndex: (value: number) => void,
  draw: () => void,
  imageSrc: string,
  originalRef: React.MutableRefObject<string>,
  setImageSrc: (value: string) => void,
  setOffset: (value: { x: number; y: number }) => void,
  computeImageLayout: () => any,
  dragging: React.MutableRefObject<null | any>,
  previewPointerIdRef: React.MutableRefObject<number | null>,
  previewOriginalRef: React.MutableRefObject<boolean>,
  setPreviewOriginal: (value: boolean) => void,
  setSelectedCategory: (category: 'basic' | 'color' | 'effects' | 'special' | 'crop' | 'frame' | 'overlays') => void,
  previousCategory: 'basic' | 'color' | 'effects' | 'special' | 'crop' | 'frame' | 'overlays'
) {
  // quick derived flag: has the user made any edits (image replaced, selection or adjustments)
  const isEdited = useMemo(() => {
    const checks = [
      imageSrc !== originalRef.current,
      !!sel,
      Math.abs(exposure) > 0.001,
      Math.abs(contrast) > 0.001,
      Math.abs(saturation) > 0.001,
      Math.abs(temperature) > 0.001,
      Math.abs(vignette) > 0.001,
      Math.abs(rotation) > 0.001,
      selectedFilter !== 'none',
      Math.abs(filterStrength - 1) > 0.001,
      Math.abs(grain) > 0.001,
      // special effects
      (pixelSize || 0) > 1,
      (ditherMethod && ditherMethod !== 'none'),
      !!asciiEnabled,
      frameThickness > 0,
      !!overlay,
      !!frameOverlay,
    ];
    return checks.some(Boolean);
  }, [imageSrc, sel, exposure, contrast, saturation, temperature, vignette, selectedFilter, filterStrength, grain, pixelSize, ditherMethod, asciiEnabled, frameThickness, originalRef, rotation, overlay, frameOverlay]);

  // Action wrappers that delegate to the standalone action helpers
  async function applyEdit() {
    setIsProcessing(true);
    await applyEditAction(
      imgRef,
      canvasRef,
      offset,
      sel,
      exposure,
      contrast,
      saturation,
      temperature,
      vignette,
      frameColor,
      frameThickness,
      selectedFilter,
      filterStrength,
      grain,
      softFocus,
      fade,
      rotation,
      rotationRef,
      overlay,
      frameOverlay,
      ditherMethod,
      ditherLevels,
      ditherColorMode,
      ditherPalette,
      ditherCustomPalette,
      pixelSize,
      pixelShape,
      pixelSample,
      asciiEnabled,
      asciiCellSize,
      asciiCharset,
      asciiInvert,
      asciiColor,
      asciiOpacity,
      asciiBackground,
      asciiFont,
      asciiGamma,
      asciiBold,
      asciiEdge,
      asciiCharsetPreset,
      onApply
    );
    setIsProcessing(false);
  }

  function resetAdjustments() {
    resetAdjustmentsAction(
      setExposure,
      exposureRef,
      setContrast,
      contrastRef,
      setSaturation,
      saturationRef,
      setTemperature,
      temperatureRef,
      setVignette,
      vignetteRef,
      setFrameColor,
      frameColorRef,
      setFrameThickness,
      frameThicknessRef,
      setSelectedFilter,
      selectedFilterRef,
      setFilterStrength,
      filterStrengthRef,
      setGrain,
      grainRef,
      setSoftFocus,
      softFocusRef,
      setFade,
      fadeRef,
      setOverlay,
      overlayRef,
      setFrameOverlay,
      frameOverlayRef,
      setRotation,
      rotationRef,
      setSel,
      cropRatio,
      setPresetIndex,
      // special
      setDitherMethod,
      ditherMethodRef,
      setDitherLevels,
      ditherLevelsRef,
      setDitherColorMode,
      ditherColorModeRef,
      setDitherPalette,
      ditherPaletteRef,
      setDitherCustomPalette,
      ditherCustomPaletteRef,
      setPixelSize,
      pixelSizeRef,
      setPixelShape,
      pixelShapeRef,
      setPixelSample,
      pixelSampleRef,
      setAsciiEnabled,
      asciiEnabledRef,
      setAsciiCellSize,
      asciiCellSizeRef,
      setAsciiCharset,
      asciiCharsetRef,
      setAsciiInvert,
      asciiInvertRef,
      setAsciiColor,
      asciiColorRef,
      setAsciiOpacity,
      asciiOpacityRef,
      setAsciiBackground,
      asciiBackgroundRef,
      setAsciiFont,
      asciiFontRef,
      setAsciiGamma,
      asciiGammaRef,
      setAsciiBold,
      asciiBoldRef,
      setAsciiEdge,
      asciiEdgeRef,
      setAsciiCharsetPreset
    );
    // ensure canvas redraw after reset
    requestAnimationFrame(() => draw());
  }

  function resetControlToDefault(control: string) {
    resetControlToDefaultAction(
      control,
      exposureRef,
      setExposure,
      contrastRef,
      setContrast,
      saturationRef,
      setSaturation,
      temperatureRef,
      setTemperature,
      filterStrengthRef,
      setFilterStrength,
      vignetteRef,
      setVignette,
      grainRef,
      setGrain,
      softFocusRef,
      setSoftFocus,
      fadeRef,
      setFade,
      setRotation,
      rotationRef,
      frameThicknessRef,
      setFrameThickness,
      draw,
      // special
      ditherMethodRef,
      setDitherMethod,
      ditherLevelsRef,
      setDitherLevels,
      pixelSizeRef,
      setPixelSize,
      asciiEnabledRef,
      setAsciiEnabled,
      asciiCellSizeRef,
      setAsciiCellSize,
      asciiCharsetRef,
      setAsciiCharset,
      asciiInvertRef,
      setAsciiInvert,
      asciiColorRef,
      setAsciiColor
    );
  }

  async function bakeRotate90() {
    await bakeRotate90Action(imgRef, setImageSrc, setSel, setOffset);
    requestAnimationFrame(() => draw());
  }

  async function bakeRotateMinus90() {
    await bakeRotateMinus90Action(imgRef, setImageSrc, setSel, setOffset);
    requestAnimationFrame(() => draw());
  }

  async function applyCropOnly() {
    await applyCropOnlyAction(
      imgRef,
      canvasRef,
      sel,
      offset,
      rotation,
      rotationRef,
      setImageSrc,
      setSel,
      setOffset,
      setRotation,
      computeImageLayout
    );
    setSelectedCategory(previousCategory);
  }

  function resetCrop() {
    resetCropAction(
      imageSrc,
      originalRef,
      setImageSrc,
      setSel,
      setOffset,
      rotationRef,
      setRotation,
      cropRatio,
      setPresetIndex,
      dragging,
      previewPointerIdRef,
      previewOriginalRef,
      setPreviewOriginal,
      computeImageLayout,
      canvasRef
    );
  }

  return {
    isEdited,
    applyEdit,
    resetAdjustments,
    resetControlToDefault,
    bakeRotate90,
    bakeRotateMinus90,
    applyCropOnly,
    resetCrop
  };
}
